### Get goals
GET http://localhost:5000/api/goals HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyODRjNjNiZjQ3YzFmYjJlNDc5YjYzYyIsImlhdCI6MTY1MjkxODgwMSwiZXhwIjoxNjU1NTEwODAxfQ.e-Yhba05HpjhUXgEvrauKQWFqJg1kcU_7FYWLrjbLAs

### Set goal
POST http://localhost:5000/api/goals HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyODRjNjNiZjQ3YzFmYjJlNDc5YjYzYyIsImlhdCI6MTY1MjkxODgwMSwiZXhwIjoxNjU1NTEwODAxfQ.e-Yhba05HpjhUXgEvrauKQWFqJg1kcU_7FYWLrjbLAs

{
  "text": "My First Goal"
}

### Update goal
PUT http://localhost:5000/api/goals/62859ebb96b4370f0616e966 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyODRjNjNiZjQ3YzFmYjJlNDc5YjYzYyIsImlhdCI6MTY1MjkxODgwMSwiZXhwIjoxNjU1NTEwODAxfQ.e-Yhba05HpjhUXgEvrauKQWFqJg1kcU_7FYWLrjbLAs

{
  "text": "My First Goal"
}

### Delete goal
DELETE  http://localhost:5000/api/goals/6283812a1aea762c4ed7fc0e HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyODRjNjNiZjQ3YzFmYjJlNDc5YjYzYyIsImlhdCI6MTY1MjkxODgwMSwiZXhwIjoxNjU1NTEwODAxfQ.e-Yhba05HpjhUXgEvrauKQWFqJg1kcU_7FYWLrjbLAs

### Register
POST http://localhost:5000/api/users HTTP/1.1
Content-Type: application/json

{
  "name": "Sujan Mridha",
  "email": "sujan.cse5.bu@gmail.com",
  "password": "sujanmridha"
}

### Login
POST http://localhost:5000/api/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "sourav.cse5.bu@gmail.com",
  "password": "souravmalo"
}

### Get user details
GET http://localhost:5000/api/users/me HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyODRjNjNiZjQ3YzFmYjJlNDc5YjYzYyIsImlhdCI6MTY1MjkxODgwMSwiZXhwIjoxNjU1NTEwODAxfQ.e-Yhba05HpjhUXgEvrauKQWFqJg1kcU_7FYWLrjbLAs